### ISSUE TITLE
Honduras flag URL has moved

### ISSUE THREAD

**Issue by jacobStankaitis** [ronatskiy/country-flags-svg#15]
This has been changed https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Honduras_(darker_variant).svg and no longer exists.

**Comment by guitartsword** [comment]
The new location is: https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg

**Comment by ronatskiy** [comment]
Bug is fixed [here](https://github.com/ronatskiy/country-flags-svg/pull/19) ✅
New version [https://www.npmjs.com/package/country-flags-svg/v/1.1.1](1.1.1) is published ✅
