### ISSUE TITLE
Node 18 Support

### ISSUE THREAD

**Issue by KieranRobson** [ronatskiy/country-flags-svg#38]
Hi! This seems to be the best flag repo however it lacks node 18 support

`error country-flags-svg@1.1.6: The engine "node" is incompatible with this module. Expected version "^12.17.0 || 13.x || 14.x || 15.x || 16.x". Got "18.12.0"`

Is there any chance of this coming?

Thanks!

**Comment by ronatskiy** [comment]
https://github.com/ronatskiy/country-flags-svg/pull/37 is merged and the new version is published

**Comment by KieranRobson** [comment]
All works, thanks!
