### ISSUE TITLE
The UK flag Not working

### ISSUE THREAD

**Issue by noureddein** [ronatskiy/country-flags-svg#41]
![image](https://user-images.githubusercontent.com/77916515/209920903-c466b3ed-ff08-40a1-a78e-7e469c4cf34c.png)

**Comment by posij118** [comment]
Had the same issue, and already posted a PR.

**Comment by lori99-data** [comment]
I have the same issue.UK is not working

**Comment by piyushverma1337** [comment]
Same issue, there is already a PR for fix please add it in.

**Comment by ronatskiy** [comment]
https://github.com/ronatskiy/country-flags-svg/pull/42 ✅
